Update readme & pre-commit
Python-Community-News/pcn_days_until_podcast_shield pull request #2
Opened 2022-10-31 02:42 UTC by kjaymiller

updates the readme to conform more to the organization standard

2022-10-31 15:25 UTC, jonafato requested changes
One change request. Additionally, (and this is minor in this case but something I'd push for in most), please try to separate unrelated changes like this. e.g. a readme change here is almost entirely unrelated to reformatting most of the repo.

2022-10-31 15:25 UTC, jonafato commented on README.md
> +![Days until Topic Deadline](https://img.shields.io/endpoint?url=https://pcn-days-until-badge.azurewebsites.net/api/badgetopicsdeadline)
```suggestion
![Days until Topic Due Date](https://img.shields.io/endpoint?url=https://pcn-days-until-badge.azurewebsites.net/api/badgetopicsdeadline)
```

Also, can we change the name used in the API call there?

2022-10-31 16:00 UTC, kjaymiller commented on README.md
> +![Days until Topic Deadline](https://img.shields.io/endpoint?url=https://pcn-days-until-badge.azurewebsites.net/api/badgetopicsdeadline)
We can definitely change the api call name but it would require rebuilding the function. Not impossible but definitely something to add in a future PR once completed.

2022-11-02 00:25 UTC, jonafato commented on README.md
> +![Days until Topic Deadline](https://img.shields.io/endpoint?url=https://pcn-days-until-badge.azurewebsites.net/api/badgetopicsdeadline)
I think this is updated now in the badge repo, correct?

2022-11-02 01:33 UTC, kjaymiller commented on README.md
> +![Days until Topic Deadline](https://img.shields.io/endpoint?url=https://pcn-days-until-badge.azurewebsites.net/api/badgetopicsdeadline)
Yes it is updated

2022-11-08 14:32 UTC, closed without merging